### ISSUE TITLE
Getting error Err((1, "Error parsing json."))

### ISSUE THREAD

**Issue by andy5995** [36den/json_minimal-rust#1]
Here's my code

```
    let config_contents = String::from(
        fs::read_to_string("./config_test.json")
            .unwrap()
            .trim()
            .to_string(),
    );
    let json = Json::parse(config_contents.as_bytes());
    print!("{}", config_contents);
    println!("{:?}", json);
```

The contents of `config_test.json`:

```
{
   "waste": [".oxi-rmw-Trash-test", "dir/example2"]
}
```

The output:

```
{
   "waste": [".oxi-rmw-Trash-test", "dir/example2"]
}Err((1, "Error parsing json."))
```

I'm unable to identify the problem.

**Comment by Lonami** [comment]
The problem is whitespace. If you remove it, it works fine (i.e. the JSON must be minified):

```
{"waste":[".oxi-rmw-Trash-test","dir/example2"]}
```

**Comment by andy5995** [comment]
Ah, ok, thanks @Lonami I'll remember that.

**Comment by Lonami** [comment]
This is still an issue in the library though, so I think it should remain open. I was only giving some feedback on the issue for anyone investigating.

**Comment by 36den** [comment]
Sorry it took so long, but version 1.3 should work for Json formatted with '\t', '\r', '\n' and ' '. Let me know if there are still issues with this.

**Comment by Lonami** [comment]
FTR, I believe the commit fixing this is https://github.com/36den/json_minimal-rust/commit/18ae15ae014f1ef5f842b7d48535afdea33c57d2.
