### ISSUE TITLE
Use question-mark operator

### ISSUE THREAD

**Issue by Lonami** [36den/json_minimal-rust#5]
The code is littered with code like the following:

```rust
match Self::parse_number(input,incr) {
    Ok(json) => {
        result.push( json );
    },
    Err(e) => {
        return Err(e);
    }
}
```

This hurts readability a lot, as it can be written a lot more concisely as follows:

```rust
result.push(Self::parse_number(input, incr)?);
```

It's equivalent in behavior.

**Comment by 36den** [comment]
Accidentally closed this one too. Will work on it.

**Comment by 36den** [comment]
Wait, didn't you do all this already?

**Comment by Lonami** [comment]
I opened issues as I found them, and made a pull request that fixed them all, yes.
